language: go

go:
  - 1.9.x
  - tip

go_import_path: github.com/Bebu1985/jsonTerritoryConverter/convert

before_install:
  - go get -t ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)