language: go

go:
  - "1.10"

go_import_path: github.com/Bebu1985/jsonTerritoryConverter

before_install:
  - go get -t ./...

script:
  - go test -race ./convert -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)